context:
  version: "3.0.0"

package:
  name: cadical
  version: ${{ version }}

source:
  url: https://github.com/arminbiere/cadical/archive/refs/tags/rel-${{ version }}.tar.gz
  sha256: 282b1c9422fde8631cb721b86450ae94df4e8de0545c17a69a301aaa4bf92fcf

build:
  number: 0
  skip: win
  script: |
    cp $RECIPE_DIR/CMakeLists.txt CMakeLists.txt
    cmake -GNinja $CMAKE_ARGS -B build -S .
    cmake --build build --config Release
    cmake --install build --prefix $PREFIX

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja

tests:
  - package_contents:
      include:
        - cadical.hpp
        - ccadical.h
        - ipasir.h
      lib:
        - cadical
      bin:
        - cadical
        - mobical

  - script:
      - cadical --version
  - script:
      - cadical simple.cnf > output.txt || EXIT_CODE=$?
      - test $EXIT_CODE -eq 20
      - cat output.txt
      - grep "s UNSATISFIABLE" output.txt
    files:
      recipe:
        - simple.cnf
  - script:
      - $CXX test.cpp $CXXFLAGS $LDFLAGS -I$PREFIX/include -lcadical -o test -std=c++11
      - ./test
    files:
      recipe:
        - test.cpp
    requirements:
      run:
        - ${{ compiler('cxx') }}

about:
  homepage: https://fmv.jku.at/cadical/
  license: MIT
  license_file: LICENSE
  summary: Clean and efficient state-of-the-art SAT solver
  description: |
    CaDiCaL is a simplified SAT solver written in C++. It is designed to be 
    clean, efficient, and easy to use. The solver is highly competitive in 
    international SAT competitions and provides both a library and a standalone 
    binary for solving SAT problems.

extra:
  recipe-maintainers:
    - wolfv
